data:
  build: ./data

db:
  image: mysql
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: nanakenashi
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: test
  ports:
    - '3306:3306'
  volumes_from:
    - data

app:
  build: ./app
  ports:
    - '8088:8088'
  links:
    - db
